'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="MDB_ASBL")>  _
Partial Public Class mdbDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.sosync.My.MySettings.Default.MDB_ASBLConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="odoo.ft_sosyncSchema_get", IsComposable:=true)>  _
	Public Function ft_sosyncSchema_get() As IQueryable(Of ft_sosyncSchema_getResult)
		Return Me.CreateMethodCallQuery(Of ft_sosyncSchema_getResult)(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo))
	End Function
End Class

Partial Public Class ft_sosyncSchema_getResult
	
	Private _TableName As String
	
	Private _FieldName As String
	
	Private _msSQLSchemaName As String
	
	Private _online_model_name As Object
	
	Private _online_model_rel_field_name As Object
	
	Private _datatype As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TableName", DbType:="NVarChar(128) NOT NULL", CanBeNull:=false)>  _
	Public Property TableName() As String
		Get
			Return Me._TableName
		End Get
		Set
			If (String.Equals(Me._TableName, value) = false) Then
				Me._TableName = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FieldName", DbType:="NVarChar(128)")>  _
	Public Property FieldName() As String
		Get
			Return Me._FieldName
		End Get
		Set
			If (String.Equals(Me._FieldName, value) = false) Then
				Me._FieldName = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_msSQLSchemaName", DbType:="NVarChar(128) NOT NULL", CanBeNull:=false)>  _
	Public Property msSQLSchemaName() As String
		Get
			Return Me._msSQLSchemaName
		End Get
		Set
			If (String.Equals(Me._msSQLSchemaName, value) = false) Then
				Me._msSQLSchemaName = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_online_model_name", DbType:="Variant", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property online_model_name() As Object
		Get
			Return Me._online_model_name
		End Get
		Set
			If (Object.Equals(Me._online_model_name, value) = false) Then
				Me._online_model_name = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_online_model_rel_field_name", DbType:="Variant", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property online_model_rel_field_name() As Object
		Get
			Return Me._online_model_rel_field_name
		End Get
		Set
			If (Object.Equals(Me._online_model_rel_field_name, value) = false) Then
				Me._online_model_rel_field_name = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_datatype", DbType:="NVarChar(128) NOT NULL", CanBeNull:=false)>  _
	Public Property datatype() As String
		Get
			Return Me._datatype
		End Get
		Set
			If (String.Equals(Me._datatype, value) = false) Then
				Me._datatype = value
			End If
		End Set
	End Property
End Class
