<?xml version="1.0" encoding="utf-8"?><Database Name="MDB_ASBL" Class="mdbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=mssql1;Initial Catalog=MDB_ASBL;Integrated Security=True" SettingsObjectName="sosync.My.MySettings" SettingsPropertyName="MDB_ASBLConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="odoo.ft_sosyncSchema_get" Method="ft_sosyncSchema_get" IsComposable="true">
    <ElementType Name="ft_sosyncSchema_getResult">
      <Column Name="TableName" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="FieldName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="msSQLSchemaName" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="online_model_name" Type="System.Object" DbType="Variant" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="online_model_rel_field_name" Type="System.Object" DbType="Variant" CanBeNull="true" UpdateCheck="Never" />
    </ElementType>
  </Function>
</Database>