//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MassDataCorrection.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MassDataCorrection.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- nur einen Einträge in der Änderung - somit nur nach ODOO aktualisieren
        ///			SELECT p.PersonID, p.sosync_fso_id FROM dbo.xAktionÄnderung ä
        ///			INNER JOIN dbo.Person p
        ///				ON ä.PersonID = p.PersonID
        ///			inner JOIN (
        ///			SELECT MAX(aktionsid)maxaktionsid, TabellenIdentity FROM dbo.xAktionÄnderung WHERE Tabellenname LIKE &apos;%Personemailgruppe%&apos;  AND Feldname LIKE &apos;gültigVon&apos;  
        ///			--AND NOT Sachbearbeiter LIKE &apos;%sosync%&apos;
        ///			GROUP BY TabellenIdentity) g ON g.maxaktionsid = ä.AktionsID
        ///			
        ///			WHERE Tabellenn [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NewsletterQuery {
            get {
                return ResourceManager.GetString("NewsletterQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ä.* INTO #up1 FROM dbo.xAktionÄnderung ä
        ///			
        ///			inner JOIN (
        ///			SELECT MAX(aktionsid)maxaktionsid, TabellenIdentity FROM dbo.xAktionÄnderung WHERE Tabellenname LIKE &apos;%Personemailgruppe%&apos;  AND Feldname LIKE &apos;gültigVon&apos;  
        ///			--AND NOT Sachbearbeiter LIKE &apos;%sosync%&apos;
        ///			GROUP BY TabellenIdentity) g ON g.maxaktionsid = ä.AktionsID
        ///			
        ///			WHERE Tabellenname LIKE &apos;%Personemailgruppe%&apos; AND Auslöser LIKE &apos;%neuanlage%&apos; AND Feldname LIKE &apos;gültigVon&apos;  AND SUBSTRING(Wertneu,12,8) &lt;&gt;&apos;00:00:00&apos;
        ///			AND ä.Dur [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpdateSosyncWriteDate {
            get {
                return ResourceManager.GetString("UpdateSosyncWriteDate", resourceCulture);
            }
        }
    }
}
