//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MassDataCorrection.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MassDataCorrection.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- count &gt; 1 wenn sosync und user beide = 1 dann retour setzen auf 31.12.2099 - Liste für Meldungen
        /// -- Kontrolle ob andere Sachbearbeiter-kombis vorhanden außer (0, &gt;= 1) , (1, 1)
        /// -- Uhrzeit bei gültig von
        ///SELECT
        ///	basis.*
        ///	,p.sosync_fso_id
        ///-- UPDATE pg SET GültigBis = &apos;20991231&apos;
        ///FROM
        ///(
        ///	SELECT
        ///		SUM(DISTINCT  CASE WHEN a.Sachbearbeiter LIKE &apos;%_sosync&apos; THEN 1 ELSE 0 end) sosync_änderungen
        ///		,SUM(DISTINCT  CASE WHEN a.Sachbearbeiter LIKE &apos;%_sosync&apos; THEN 0 ELSE 1 end) user_änderungen
        ///		,a.PersonI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GruppenQuery {
            get {
                return ResourceManager.GetString("GruppenQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO sosync.JobQueue
        ///(
        ///    JobDate,
        ///    JobSourceSystem,
        ///    JobSourceModel,
        ///    JobSourceRecordID,
        ///    JobState,
        ///    JobSourceSosyncWriteDate,
        ///    JobSourceFields,
        ///    JobSourceTargetRecordID,
        ///    JobSourceMergeIntoRecordID,
        ///    JobSourceTargetMergeIntoRecordID,
        ///    JobSourceType
        ///)
        ///VALUES
        ///(   @sosyncWriteDate, -- JobDate - datetime2(7)
        ///    @system,            -- JobSourceSystem - varchar(32)
        ///    @model,           -- JobSourceModel - nvarchar(128)
        ///    @ID,             -- JobSourceRe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InsertSyncJobMSSQL {
            get {
                return ResourceManager.GetString("InsertSyncJobMSSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO sosync.JobQueue
        ///(
        ///    JobDate,
        ///    JobSourceSystem,
        ///    JobSourceModel,
        ///    JobSourceRecordID,
        ///    JobState,
        ///    JobSourceSosyncWriteDate,
        ///    JobSourceFields
        ///)
        ///SELECT
        ///    p.sosync_write_date JobDate,
        ///    &apos;fs&apos; JobSourceSystem,
        ///    &apos;%MODEL%&apos; JobSourceModel,
        ///    p.%MODELID% JobSourceRecordID,
        ///    &apos;new&apos; JobState,
        ///    p.sosync_write_date JobSourceSosyncWriteDate,
        ///    N&apos;{&quot;info&quot;:&quot;%INFO%&quot;}&apos; JobSourceFields
        ///
        ///FROM
        ///	%MODEL% p
        ///WHERE
        ///	p.%MODELID% IN (
        ///	%ID-LIST%
        ///	).
        /// </summary>
        internal static string InsertSyncJobMSSQLBatch {
            get {
                return ResourceManager.GetString("InsertSyncJobMSSQLBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO sosync.JobQueue
        ///(
        ///    JobDate,
        ///    JobSourceSystem,
        ///    JobSourceModel,
        ///    JobSourceRecordID,
        ///    JobState,
        ///    JobSourceSosyncWriteDate,
        ///    JobSourceFields,
        ///    JobSourceTargetRecordID
        ///)
        ///SELECT
        ///    m.sosync_write_date JobDate,
        ///    &apos;fs&apos; JobSourceSystem,
        ///    &apos;STUDIOMODEL&apos; JobSourceModel,
        ///    m.STUDIOMODELID JobSourceRecordID,
        ///    &apos;new&apos; JobState,
        ///    m.sosync_write_date JobSourceSosyncWriteDate,
        ///    &apos;{&quot;info&quot;:&quot;MassDataCorrection-App&quot;}&apos; JobSourceFields,
        ///    m.sosync_fso_id JobSo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InsertSyncJobMSSQLTempTable {
            get {
                return ResourceManager.GetString("InsertSyncJobMSSQLTempTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE pg SET GültigBis = &apos;20991231&apos;
        ///FROM
        ///(
        ///	SELECT
        ///		SUM(DISTINCT  CASE WHEN a.Sachbearbeiter LIKE &apos;%_sosync&apos; THEN 1 ELSE 0 end) sosync_änderungen
        ///		,SUM(DISTINCT  CASE WHEN a.Sachbearbeiter LIKE &apos;%_sosync&apos; THEN 0 ELSE 1 end) user_änderungen
        ///		,a.PersonID
        ///		,a.TabellenIdentity
        ///	FROM
        ///		(SELECT * FROM dbo.xAktionÄnderung WHERE Tabellenname = &apos;PersonGruppe&apos; AND Feldname = &apos;GültigVon&apos; ) a
        ///		INNER JOIN (SELECT * FROM dbo.xAktionÄnderung WHERE Tabellenname = &apos;PersonGruppe&apos; AND WertNeu like &apos;%&lt;128782&gt;&apos;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpdateSosyncWriteDate {
            get {
                return ResourceManager.GetString("UpdateSosyncWriteDate", resourceCulture);
            }
        }
    }
}
